name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_POND_094D4CA03 }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: upload
            app_location: blog
            output_location: _site
            production_branch: main
        env:
            JEKYLL_ENV: production
      - name: Output URL
        run: echo $AZURE_STATIC_WEB_APPS_URL
